import "User.idl";

namespace Pine
{
    [default_interface]
    runtimeclass PineClient
    {
        PineClient();

        User CurrentUser{ get; };

        Windows.Foundation.Collections.IObservableVector<User> Contacts{ get; };

        Windows.Foundation.IAsyncAction FetchCurrentUserAsync();
        Windows.Foundation.IAsyncAction LoginAsync(String id, String password);
        Windows.Foundation.IAsyncAction SignUpAsync(String id, String password);
    };
}